"""add attrs in Post

Revision ID: 550d1111f9c8
Revises: d11cd6122973
Create Date: 2022-11-22 14:11:24.066825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550d1111f9c8'
down_revision = 'd11cd6122973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('detail', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_price'), ['price'], unique=False)
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_index(batch_op.f('ix_post_price'))
        batch_op.drop_index(batch_op.f('ix_post_category'))
        batch_op.drop_column('detail')
        batch_op.drop_column('price')
        batch_op.drop_column('category')
        batch_op.drop_column('image_url')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
