"""update column comment

Revision ID: 793feed0a9be
Revises: db693f050142
Create Date: 2022-11-22 17:06:20.694799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793feed0a9be'
down_revision = 'db693f050142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=140), nullable=True))
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
